

export const PROJECTS_LIST_POPULATE     = 'PROJECTS_LIST_POPULATE';
export const PROJECTS_FORM_POPULATE     = 'PROJECTS_FORM_POPULATE';
export const PROJECTS_FORM_RESET        = 'PROJECTS_FORM_RESET';
export const PROJECTS_FORM_FIELD_EDIT   = 'PROJECTS_FORM_FIELD_EDIT';
export const PROJECTS_ERRORS_POPULATE   = 'PROJECTS_ERRORS_POPULATE';

export const ASSOC_SET      = 'ASSOC_SET';
export const ASSOC_DELETE   = 'ASSOC_DELETE';