

export const PROJECTS_LIST_POPULATE = 'PROJECTS_LIST_POPULATE';
export const PROJECTS_FORM_POPULATE = 'PROJECTS_FORM_POPULATE';
export const PROJECTS_POPULATE_ERRORS = 'PROJECTS_POPULATE_ERRORS';
export const PROJECTS_FORM_RESET = 'PROJECTS_FORM_RESET';
export const PROJECTS_FORM_EDIT_FIELD = 'PROJECTS_FORM_EDIT_FIELD';

export const ASSOC_SET      = 'ASSOC_SET';
export const ASSOC_DELETE   = 'ASSOC_DELETE';